#!/bin/bash
#SBATCH --job-name=101
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=2
#SBATCH --ntasks=2
#SBATCH -p grafite

module load openmpi/4.1.5-gcc-12.2.0-ptk6i3e
module load vasp/6.2.0

export OMP_NUM_THREADS=1

mpirun -np $SLURM_NTASKS vasp_std 

